url: "https://construyetucasa.github.io/mx/" # the base hostname & protocol for your site
title: Fraude construye tu casa
description: Fraude Marco Antonio Perez Alejo Puebla
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap