url: "https://construyetucasa.github.io/mx/" # the base hostname & protocol for your site
title: construye tu casa
description: Fraude, Marco Antonio Perez Alejo, Construye tu casa, Construye tu depa, University Depas, Puebla
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap